### ISSUE TITLE
Ergebnisdarstellung

### ISSUE THREAD

**Issue by Salocinf** [TimoScheuermann/Fruit-Vegetable-Identifier#2]
- Bild anzeigen 
- Name der Klasse + Genauigkeit
- Nährwerte
  - Datenmodell: Kalorien, Kohlenhydrate, Fette, Proteine, Zucker
- Allgemeine Infos
  - Stringarray

**Comment by TimoScheuermann** [comment]
Programmiertechnisch abgeschlossen
